### ISSUE TITLE
[NGO Profile] List of County/City has mistakes

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#304]
**Describe the bug**
In NGO profile > General info, when choosing County and City, for Bucharest the info is wrong. 

**Expected behavior**
Judet: Municipiul Bucuresti / Oras: Bucuresti
Also other mistakes found in the list

**Screenshots**
<img width="697" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/24204126-2bec-4531-85e6-2416390ceeb2">

**Recommended**
A check for the whole list?

**Comment by radulescuandrew** [comment]
Removed Pipera from Bucuresti. We are using this list for multiple clients, it may not fit your needs.

You can change it as per your requirements before seeding it to the production environment (for example can add "Sector 1,2, etc" instead of Pipera). Below you can find the 2 files with "Judete" and "Orase".

https://github.com/code4romania/onghub/blob/develop/backend/src/migrations/seed/counties.sees.ts
https://github.com/code4romania/onghub/blob/develop/backend/src/migrations/seed/city.seed.ts

**Comment by birloiflorian** [comment]
To validate with Andrei.
