### ISSUE TITLE
[NGO profile] User can click to on 'download list' even if there's no list to download (My NGO > Open Data > Partners and Sponsors lists)

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#333]
Current behaviour:
https://github.com/code4romania/onghub/assets/95479576/39813e22-c9e7-4ea2-805e-ae506c630430
It's not critical but can be improved

Expected behaviour:
User should not be able to click the 'Download list' button when there s no list to download.

**Comment by overeha** [comment]
This is still happening i think. it downloads an HTML
<img width="297" alt="Screenshot 2023-11-16 at 12 55 57" src="https://github.com/code4romania/onghub/assets/45068169/a472774f-15fc-42bd-8974-a9fcb898c530">

**Comment by dragos1195** [comment]
@overeha @anastk-code4 @radulescuandrew 

Only case I could find was by being logged in as an Employee and having the "download list" available on investors, but any other way (admin and super-admin) the lists were displayed as disabled. 

The fix was done by @biggicode on PR for 333.

The scenario with "data.html" could not be reproduced.
