### ISSUE TITLE
[Employees] Sending an invite wouldn't work and not showing an error

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#358]
**Describe the bug**

**Steps to reproduce the behavior**
1. Login as NGO
2. Click on Users in the sidebar menu
3. Click on Add user button
4. Fill in with info (see example in the screenshot)
5. Click on Send button
6. Task is not performed, and no error messages appear

**Expected behavior**
Show an error message or perform the task.

**Screenshots**
https://github.com/code4romania/onghub/assets/95479576/47837998-667c-452b-87ff-a7e63545dc00
*email field might have a special character

**Comment by radulescuandrew** [comment]
Indeed the email you're using, has a special character (plus, minus) which passes our validation regex. 
We are using the [RFC 5322](https://www.ietf.org/rfc/rfc5322.txt) compliant regex from https://emailregex.com/ which is also used by AWS Cognito.

The problem is that Cognito is creating the user but sending the confirmation code via email, is failing. 

We added additional validation to display an error if this will ever happen. Please test again.

There is no bulletproof regex for emails, so for a more robust validation approach, especially in the context of server-side validation or critical applications, combining regex validation with additional verification methods like sending a confirmation email is recommended.

**Comment by radulescuandrew** [comment]
@overeha @anastk-code4

**Comment by overeha** [comment]
Let's see how this behaves in real life and we can decide for a future version
