### ISSUE TITLE
Log out from all apps once logged out in ONGHUB

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#402]
As an user, I want to be logged out from every app in ONGHub that requires login, when I log out of ONGHUB webapp

**Comment by radulescuandrew** [comment]
@anastk-code4 @overeha Now when the user logs out from ONGHub, we'll do a Global SignOut. This means, the Refresh Tokens will be invalidated and the user will be able to use the other app (e.g. TEO) for the time the AccessToken is valid (that can't be invalidated on the fly). 

I changed the AccessToken validity from 1 day to 5 minutes. 

Otherwise please imagine the following: You are connected using Facebook, to a separate 3rd party application. If you log out of Facebook, you don't really want to be logged out from all applications using this authentication type. 

Still, with this implementation, the user will be able to hold maximum 5 more minutes in the app, usually much less if the token was not refreshed.

**Comment by MarG66** [comment]
@anastk-code4 For VIC this needs to be changed in Terraform Cognito from 1 day to 5 min.

**Comment by MarG66** [comment]
@overeha @mirunaioana-msc @AnaBlidaru  Please advise here, after discussions we are keeping the token validity at 1h. We believe it's not necessary to log out the users from all apps when logging out of NGO Hub.

**Comment by mirunaioana-msc** [comment]
We should set the logout token to 1h (instead of 1 day / 5 mins) in order to make sure that even if we can't sign out an NGO admin from all apps, they will be automatically signed out after 1h of inactivity.

**Comment by radulescuandrew** [comment]
@mirunaioana-msc Just to make sure we're on the same page. The regular users won't be singed out after 1h of inactivity. There are 2 tokens involved in the JWT Authentication.

1. Auth Token - Validity 1h 
2. Refresh Token - Validity 30 days

In a regular flow, once the Auth Token is expired, the application will try to regenerate the token using the Refresh Token. This is a regular, standard way of handling JWT authentication.

In our case, we are invalidating the Refresh Token when we're logging out the users so they will not be able to refresh the authentication token. 


@MarG66 please make sure the Token validity is 1h and close this issue.

**Comment by MarG66** [comment]
On it

**Comment by MarG66** [comment]
Auth Token validity is 1h on NGO Hub
