### ISSUE TITLE
[SuperAdmin/Applications] The formatting of an application's long description is minimal

### ISSUE THREAD

**Issue by mirunaioana-msc** [code4romania/onghub#475]
### **Context**
Currently, the SuperAdmin has very limited possibilities to format the text for the long description of an application. Because the purpose of this field is to display not only a descriptive text but also a list of features and/or other information, we need to have extensive formatting options such as: bold/italic/underline, bulleted list, numbered list, link on text etc. 

### **Expected behaviour**
A superadmin should be able to have multiple formatting options for this field in order to be able to provide a more comprehensive description of an application. 

As a suggestion, for other apps we previously used TinyMCE - https://www.tiny.cloud/docs/tinymce/latest/full-featured-open-source-demo/

**Comment by luciatugui** [comment]
Hello, we are currently working on this issue and there are a few things to keep in mind:

- because the content inside the editor is now HTML instead of plain text, the validations for min/max characters are no longer accurate, as more characters are being added with every new element. Therefore, we removed the min validation but still left the 7k character max limit, if you think that needs to be increased, please let us know
- if necessary, we could perform validations for the text inside the HTML tags, but don't really see an advantage in this case
