### ISSUE TITLE
[Applications] Add a new label for on-demand applications

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/onghub#476]
**Is your feature request related to a problem? Please describe.**

Some apps in NGO Hub are available on-demand, in case of a crisis or other events.
These apps currently have the "coming soon" label, which doesn't show the actual situation.

**Describe the solution you'd like**

A new type of label should exist for this purpose, **the name of the label is TBD**.

**Comment by radulescuandrew** [comment]
@tudoramariei @anastk-code4 Now we manage the display of the application using a status `active` or `disabled`. 

The `disabled` are displayed with the `Coming Soon` badge.

Solution: Add a new status `on-demand` to display the `Coming soon` badge. The `disabled` status will hide the app.

Please advise.

**Comment by mirunaioana-msc** [comment]
Here I created a short design. 
Please see Figma here - https://www.figma.com/design/cfixQXmZ7FdFatiDCpUhyK/ONG-HUB?node-id=8672-19980&t=kcM88bkdIEWComoc-4 

Basically I suggest adding in the creating/editing app page a section called App Status in which the SuperAdmin can choose if the app is active or not, where Active = available for NGOs to add on their profiles and Inactive = not available for NGOs to add in their profile + the SuperAdmin can add a label which can be put on the card app, without having these 2 (status and label dependent on each other). With the mention that an Inactive app should have this description on its page: "Aplicația este inactivă.  Momentan, această aplicație nu este încă disponibilă. Vom reveni cu noutăți în curând." instead of the one suggesting that it is in development.

**Comment by radulescuandrew** [comment]
@mirunaioana-msc if this is duplicated, please delete.

**Comment by andrei-manda** [comment]
Duplicated by https://github.com/code4romania/onghub/issues/495
